/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import Knight from "../assets/KnightPiece.glb";

type GLTFResult = GLTF & {
	nodes: {
		Cube: THREE.Mesh;
	};
	materials: {
		Black: THREE.MeshStandardMaterial;
	};
};

export function KnightPiece(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(Knight) as GLTFResult;
	return (
		<group
			{...props}
			dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cube.geometry}
				material={materials.Black}
				position={[3.984, 0.059, -0.035]}
				scale={0.314}
			/>
		</group>
	);
}

useGLTF.preload(Knight);
