/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import Queen from "../assets/QueenPiece.glb";

type GLTFResult = GLTF & {
	nodes: {
		Circle003: THREE.Mesh;
	};
	materials: {
		Black: THREE.MeshStandardMaterial;
	};
};

export function QueenPiece(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(Queen) as GLTFResult;
	return (
		<group
			{...props}
			dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Circle003.geometry}
				material={materials.Black}
				position={[0.653, 0, -0.035]}
			/>
		</group>
	);
}

useGLTF.preload(Queen);
