/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import Menu from "../assets/SipnPlay_Feature_Menu.glb";

type GLTFResult = GLTF & {
	nodes: {
		Plane006: THREE.Mesh;
		Plane007: THREE.Mesh;
		Plane009: THREE.Mesh;
		Plane009_1: THREE.Mesh;
		Cylinder007: THREE.Mesh;
		Cylinder007_1: THREE.Mesh;
		Cylinder007_2: THREE.Mesh;
		Cylinder007_3: THREE.Mesh;
		Cylinder007_4: THREE.Mesh;
		Cylinder001_1: THREE.Mesh;
		Cylinder001_2: THREE.Mesh;
		Cylinder002: THREE.Mesh;
		Plane008: THREE.Mesh;
		Plane012: THREE.Mesh;
		Circle023: THREE.Mesh;
		Circle023_1: THREE.Mesh;
		Circle023_2: THREE.Mesh;
		Circle023_3: THREE.Mesh;
		Circle008_1: THREE.Mesh;
		Circle008_2: THREE.Mesh;
	};
	materials: {
		DarkBrown: THREE.MeshStandardMaterial;
		Black: THREE.MeshStandardMaterial;
		white: THREE.MeshStandardMaterial;
		BobaMaterial: THREE.MeshStandardMaterial;
		["Transparent.001"]: THREE.MeshPhysicalMaterial;
		BubbleMaterial: THREE.MeshStandardMaterial;
		Brown: THREE.MeshStandardMaterial;
		Red: THREE.MeshStandardMaterial;
		Fries: THREE.MeshStandardMaterial;
		Bun: THREE.MeshStandardMaterial;
		cheese: THREE.MeshStandardMaterial;
		Seed: THREE.MeshStandardMaterial;
		["Meat.001"]: THREE.MeshStandardMaterial;
		Transparent: THREE.MeshPhysicalMaterial;
	};
};

export function Menu3D(props: JSX.IntrinsicElements["group"]) {
	const { nodes, materials } = useGLTF(Menu) as GLTFResult;
	return (
		<group
			{...props}
			dispose={null}>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane006.geometry}
				material={materials.Black}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane007.geometry}
				material={materials.DarkBrown}
				position={[4.593, 3.577, -5.828]}
				scale={[1, 2.041, 1]}
			/>
			<group position={[4.118, 3.955, -5.774]}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane009.geometry}
					material={materials.Black}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Plane009_1.geometry}
					material={materials.white}
				/>
			</group>
			<group
				position={[8.849, 5.292, -3.818]}
				rotation={[0, 1.5, 0]}
				scale={2.079}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder007.geometry}
					material={materials.BobaMaterial}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder007_1.geometry}
					material={materials["Transparent.001"]}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder007_2.geometry}
					material={materials.white}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder007_3.geometry}
					material={materials.Black}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder007_4.geometry}
					material={materials.BubbleMaterial}
				/>
			</group>
			<group
				position={[8.586, 5.124, -1.145]}
				rotation={[0, 1.5, 0]}
				scale={2.279}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder001_1.geometry}
					material={materials.Brown}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Cylinder001_2.geometry}
					material={materials.DarkBrown}
				/>
			</group>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Cylinder002.geometry}
				material={materials.Black}
				position={[8.586, 5.124, -1.145]}
				rotation={[0, 1.5, 0]}
				scale={2.279}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane008.geometry}
				material={materials.Red}
				position={[9.043, 4.656, -8.604]}
				rotation={[Math.PI, -1.5, Math.PI]}
				scale={1.074}
			/>
			<mesh
				castShadow
				receiveShadow
				geometry={nodes.Plane012.geometry}
				material={materials.Fries}
				position={[8.907, 5.186, -8.39]}
				rotation={[-2.47, -1.486, -2.56]}
				scale={1.074}
			/>
			<group
				position={[8.959, 4.258, -5.987]}
				rotation={[0, 1.5, 0]}
				scale={2.063}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Circle023.geometry}
					material={materials.Bun}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Circle023_1.geometry}
					material={materials.cheese}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Circle023_2.geometry}
					material={materials.Seed}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Circle023_3.geometry}
					material={materials["Meat.001"]}
				/>
			</group>
			<group
				position={[9.316, 4.345, -10.852]}
				rotation={[0, 1.5, 0]}
				scale={2.843}>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Circle008_1.geometry}
					material={materials.Transparent}
				/>
				<mesh
					castShadow
					receiveShadow
					geometry={nodes.Circle008_2.geometry}
					material={materials.Black}
				/>
			</group>
		</group>
	);
}

useGLTF.preload(Menu);
